# Machine Learning Fundamentals - Linear Algebra - Exercise: Matrix and Vector Operations

## Table of Contents
* [Introduction](#Introduction)
* [Requirements](#Requirements) 
  * [Knowledge](#Knowledge) 
  * [Modules](#Python-Modules)
  * [Data](#Data)
* [Exercise: Pen and Paper Calculation](#Pen-and-Paper-Calculation)
* [Exercise: Implementation of Basic Operations](#Implmentation-of-Basic-Operations)
  * [Vector Addition](#Vector-Addition)
  * [Vector Subtraction](#Vector-Subtraction)
  * [Scalar Multiplication](#Scalar-Multiplication)
  * [Dot Product](#Dot-Product)
  * [Matrix Multiplication](#Matrix-Multiplication)
  * [Transpose](#Transpose)
* [Summary and Outlook](#Summary-and-Outlook)
* [Literature](#Literature) 
* [Licenses](#Licenses) 

## Introduction
This exercise tests knowledge in basics in linear algebra. Knowledge about matrices, vectors, and their operations are essential in understanding more complex machine learning topics, like neural networks. Safe handling of domain-specific notation and concepts is therefore necessary.  

## Requirements

### Knowledge

- Chapter 2 of [Deep Learning](http://www.deeplearningbook.org/contents/ml.html) by Ian Goodfellow gives a brief introduction into the field
- [Linear Algebra](http://joshua.smcvt.edu/linearalgebra/#current_version) by Jim Hefferson is a open-source textbook with a lot of good exercises
- [Introduction to Linear Algebra](http://math.mit.edu/~gs/linearalgebra/) by Gilbert Strang ist a good domain specific textbook
- [Coding the Matrix: Linear Algebra through Applications to Computer Science](http://codingthematrix.com/) by Philip Klein is focused on a computer science viewpoint

### Python Modules

In [3]:
# External Modules
import numpy as np

### Data
Given are the following matrice:

\begin{equation}
    A =
    \begin{pmatrix}
    4 & 4 & 5 \\
    2 & 1 & 7 \\
    4 & 8 & 3
    \end{pmatrix}
    ,
    B =
    \begin{pmatrix}
    1 & 6 \\
    3 & 1 \\
    5 & 2
    \end{pmatrix}
    ,
    C =
    \begin{pmatrix}
    1 & 4 & 4 \\
    3 & 1 & 2\\
    6 & 7 & 1
    \end{pmatrix}
\end{equation}


and following vectors:

\begin{equation}
    \vec{x} =
    \begin{pmatrix}
    9 \\
    5 \\
    7
    \end{pmatrix}
    ,
    \vec{y} =
    \begin{pmatrix}
    3 \\
    1 \\
    5
    \end{pmatrix}
\end{equation}

In [5]:
# Matrices
A = ([4,4,5],
     [2,1,7],
     [4,8,3])

B = ([1,6],
     [3,1],
     [5,2])

C = ([1,4,4],
     [3,1,2],
     [6,7,1])

# Vectors
x = (9,5,7)
y = (3,1,5)

In [10]:
#np vector
x = np.array([9,5,7])
y = np.array([3,1,5])
print(x.dot(y))# нельзя?
print(x.dot(y.T))

# np matrixes
A = np.array(A)
B = np.array(B)
C = np.array(C)
print(A.dot(B))
#print(B.dot(A.T)) # нельзя
print(A.dot(C))
print(C.dot(A))
print(C.T.dot(A.T).T)
print(A*C) # Hadamard/Shur Product

67
[[41 38]
 [40 27]
 [43 38]]
[[46 55 29]
 [47 58 17]
 [46 45 35]]
[[28 40 45]
 [22 29 28]
 [42 39 82]]
[[46 55 29]
 [47 58 17]
 [46 45 35]]
[[ 4 16 20]
 [ 6  1 14]
 [24 56  3]]


## Pen and Paper Calculation
Solve following calculations by hand or write some latex in that notebook.

1.  $\vec{x} * \vec{y}$ (dot or inner product)
2.  $\vec{x} * \vec{y}^T$
3.  $A * B$
4.  $B * A$
5.  $A * C$
6.  $C * A$
7.  $(C^T * A^T)T$
8.  $A \circ C$ (Hadamard or Schur product)
9.  $ \left  \langle A,C \right \rangle_F $ (Frobenius inner product)

## Implmentation of Basic Operations
Implement the following functions using the data structure `List` only. The results should be the same as the corresponding Numpy implementation.

### Vector Addition

In [93]:
# Vectors
x = (9,5,7)
y = (3,1,5)
# list
a = list([9,5,7])
b = list([3,1,5])

def vector_add(a, b):
    ''' Adds two given vectors a and b: https://en.wikipedia.org/wiki/Euclidean_vector
    
    params:
        a: A list representing vector a
        b: A list representing vector b
    returns:
        [x_1 + y_1, x_2 + y_2, ... , x_n + y_n]
    '''
    l = list([])
    for i, item in enumerate(a):
        l.append(a[i] + b[i])
            
    return l

# Test
np.testing.assert_array_almost_equal(vector_add(a,b), np.add(x,y), verbose=True)

### Vector Subtraction

In [96]:
# Vectors
x = (9,5,7)
y = (3,1,5)
# list
a = list([9,5,7])
b = list([3,1,5])

def vector_sub(a, b):
    ''' Subtracts two given vectors a and b: https://en.wikipedia.org/wiki/Euclidean_vector
    
    params:
        a: A list representing vector a
        b: A list representing vector b
    returns:
        [x_1 - y_1, x_2 - y_2, ... , x_n - y_n]
    '''
    l = list([])
    for i, item in enumerate(a):
        l.append(a[i] - b[i])
        
    return l

# Testing
np.testing.assert_array_almost_equal(vector_sub(a,b), np.subtract(x,y), verbose=True)

### Scalar Multiplication

In [147]:
B = ([4,4,5],
     [2,1,7],
     [4,8,3])

A = ([4,4,5],
     [2,1,7],
     [4,8,3])

print(np.multiply(sca,A))

def scalar_mul(r, A):
    ''' Multiply each element of a matrix or vector by a scalar 'r': https://en.wikipedia.org/wiki/Scalar_multiplication
    
    params:
        r: Scalar
        A: Vector or matrix
    returns:
         A vector or matrix with the same dimesion like 'A' but each element multiplied by r
    '''
    

    for i, item in enumerate(A):
        for j, item2 in enumerate(item):
            A[i][j] = A[i][j]*r
    
    return np.array(A)

# Testing
sca = 3
np.testing.assert_array_almost_equal(scalar_mul(sca,B), np.multiply(sca,A), verbose=True)

[[12 12 15]
 [ 6  3 21]
 [12 24  9]]
[[12 12 15]
 [ 6  3 21]
 [12 24  9]]


### Dot Product

In [164]:
x = (9,5,7)
y = (3,1,5)

def vec_dot(a, b):
    ''' Sum of the product of corresponding elements: https://en.wikipedia.org/wiki/Dot_product
    
    params:
        a: Vector 
        b: Vector
    returns:
        x_1 * y_1 + x_2 * y_2 + ... + x_n * y_n 
    ''' 
    l = list([])
    for i, item in enumerate(a):
        for j, item2 in enumerate(b):
            l.append(a[i] * b[i])
            break
    
    d = 0
    for c in l:
        d = d + c
    
    return d
    

# Testing
np.testing.assert_array_almost_equal(vec_dot(x,y), np.dot(x,y), verbose=True)

### Matrix Multiplication

In [214]:
# Matrices
A = ([4,4,5],
     [2,1,7],
     [4,8,3])

B = ([4,4,5],
     [2,1,7],
     [4,8,3])

C = ([4,4,5],
     [2,1,7],
     [4,8,3])


print(np.matmul(A,B))

def matrix_mult(A, B):
    ''' Computes the product of two matrices: https://en.wikipedia.org/wiki/Matrix_multiplication 
    
    params:
        A: Matrix with dimensions NxP
        B: Matrix with dimensions PxM
    returns:
        NxM matrix with each element c_i_j = a_i_1 * b_1_j + ... + a_i_p * b_p_j
    ''' 
    # transpose second matrix and do vec_dot
    
    B = matrix_transpose(B)
    
    matrix = C
    
    for i, item in enumerate(A):
        for j, item2 in enumerate(B):
            matrix[i][j] = vec_dot(item, item2)
            
    print(matrix)
    
    return matrix

# Testing
np.testing.assert_array_almost_equal(matrix_mult(A,B), np.matmul(A,B), verbose=True)

[[44 60 63]
 [38 65 38]
 [44 48 85]]
([44, 60, 63], [38, 65, 38], [44, 48, 85])


### Transpose

In [11]:
A = ([4,4,5],
     [2,1,7],
     [4,8,3])

B = ([1,6],
     [3,1],
     [5,2])

C = ([1,3,5],
     [6,1,2])


def matrix_transpose(A):
    ''' Flips the matrix over its diagonal, switches the row and column indices of the matrix: https://en.wikipedia.org/wiki/Transpose
    
    params:
        A: Matrix 
    returns:
        Transpose A^T of given matrix A
    ''' 
    num_iter = len(A[0])
    
    matrix = list([])
    for i in range(num_iter):
        row = list([])
        for j, item in enumerate(A):
            row.append(item[i])
        
        matrix.append(row)
    
    return np.array(matrix)

# Testing
np.testing.assert_array_almost_equal(matrix_transpose(A), np.transpose(A), verbose=True)

## Summary and Outlook

This exercise covered basic operations on vectors and matrices. If the exercise was too complicated, consider the sources mentioned above for a recap. 

## Licenses

### Notebook License (CC-BY-SA 4.0)

*The following license applies to the complete notebook, including code cells. It does however not apply to any referenced external media (e.g., images).*

Exercise: Matrix and Vector Operations <br/>
by Benjamin Voigt <br/>
is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-sa/4.0/).<br/>
Based on a work at https://gitlab.com/deep.TEACHING.


### Code License (MIT)

*The following license only applies to code cells of the notebook.*

Copyright 2018 Benjamin Voigt

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.